# Generated by Django 4.1.1 on 2022-12-13 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='position',
        ),
    ]
