# Generated by Django 4.1.1 on 2022-12-30 13:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'ordering': ['id'], 'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='aboutustranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'О нас Translation'},
        ),
        migrations.AlterField(
            model_name='carousel',
            name='position',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Позиция в карусели (0 - не отображать)'),
        ),
        migrations.AlterField(
            model_name='projecttranslation',
            name='howto',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, verbose_name='Как добраться'),
        ),
    ]
