# Generated by Django 4.1.1 on 2022-12-30 13:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_aboutus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttranslation',
            name='howto',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, verbose_name='Как добраться'),
        ),
    ]
